ctx: http://localhost:8084/flowadmin
cebxHtmlExe: E:\cebxTool\cebx2Html\Cebx2Html.exe
targetCebxDir: F:\cebxHtml
styleUrl: F:\style
uploadXml: F:\upload\flow\xml
uploadEpub: F:\upload\flow\epub
uploadCebx: F:\upload\flow\cebx
bookDetect: F:\bookDetect
batchSize: 100
threadTime: 3