ctx: http://172.18.89.115:8084/flowadmin
cebxHtmlExe: /apabi/flow/cebxTool/cebx2Html/Cebx2Html.exe
targetCebxDir: /apabi/flow/cebxHtml
styleUrl: /apabi/flow/file/book
uploadXml: /upload/flow/xml
uploadEpub: /upload/flow/epub
uploadCebx: /upload/flow/cebx
upAuthFile: /upload/flow/auth
email: /apabi/flow/file/email
batchSize: 1000
threadTime: 1